language: node_js
node_js:
  - stable
before_install:
  - openssl aes-256-cbc -K $encrypted_5f984f3b91fe_key -iv $encrypted_5f984f3b91fe_iv
    -in id_rsa.enc -out ./deploy_key -d
  - eval "$(ssh-agent -s)"
  - chmod 600 ./deploy_key
  - ssh-add ./deploy_key
  - echo "hello" >> travis-test.txt
  - git pull
