language: node_js
node_js:
- stable
before_install:
- openssl aes-256-cbc -K $encrypted_5f984f3b91fe_key -iv $encrypted_5f984f3b91fe_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
after_install:
- ssh-agent .travis/deploy.sh
