language: node_js
node_js:
- stable
before_install:
- openssl aes-256-cbc -K $encrypted_5f984f3b91fe_key -iv $encrypted_5f984f3b91fe_iv
  -in travis_rsa.enc -out .travis/travis_rsa -d
after_install:
- ssh-agent .travis/deploy.sh
